---
title: "QMEEProject_MomPupInteractions_StatsAnalyses"
author: "Tang Tang & Iman"
date: "2026-03-13"
output: html_document
---

## Library
```{r include = FALSE}

library(ggplot2)
library(dplyr)
library(stringr)
library(tidyr)
library(patchwork)

library(lme4)
library(glmmTMB)
library(DHARMa)
library(splines)
library(ggeffects)
library(MASS)


```

```{r}

MomPupBehav <- readRDS("MomPupInteractionBehav_CumulativeDataset.rds")

MomPupBehav <- MomPupBehav %>% 
 dplyr::select(-Subject)
  
summary(MomPupBehav)

```

## Mom/Pup Initiation 

### DataFrame
```{r}

MomPupInitiation_behavs <- c("MOM INITIATION", "PUP INITIATION")

MomPupInitiation <- MomPupBehav %>% 
  filter(Behaviour %in% MomPupInitiation_behavs) %>% 
  dplyr::select(-Duration_s, -Stop_s, -Start_s, -BehaviourType, -Subject)

```

```{r warning = FALSE}

MomPupInitiation_model_00 <- glm(
  Behaviour ~ Condition * PND,
  data = MomPupInitiation, 
  family = binomial(link = "logit"))

MomPupInitiation_model_01 <- glmer(
  Behaviour ~ Condition * PND +
    (1|MomID/PupID),
  data = MomPupInitiation, 
  family = binomial(link = "logit"))

MomPupInitiation_model_02 <- glmer(
  Behaviour ~ Condition * PND +
    (1+PND|MomID) + (1|PupID),
  data = MomPupInitiation, 
  family = binomial(link = "logit")) 

MomPupInitiation_model_03 <- glmer(
  Behaviour ~ Condition * PND +
    (1+PND|MomID) + 
    (1+Condition|PupID),
  data = MomPupInitiation, 
  family = binomial(link = "logit")) #this one

anova(MomPupInitiation_model_03, MomPupInitiation_model_02)

plot(simulateResiduals(MomPupInitiation_model_03))
plot(simulateResiduals(MomPupInitiation_model_02))



summary(MomPupInitiation_model_02)

```

### Visualizations

```{r}

MomPupInitiation_vis <- MomPupInitiation %>% 
  filter(Behaviour %in% MomPupInitiation_behavs) %>% 
  mutate(Choice = ifelse(Behaviour == "MOM INITIATION", 1,0)) # 1 = mom, 0 = pup

# Double vs Single
ggplot(MomPupInitiation_vis,
       aes(PND, Choice, color = Condition, fill = Condition)) +
  geom_jitter(
    position = position_jitterdodge(
      jitter.height = 0.05, jitter.width = 0.5, dodge.width = 0.5
    ),
    alpha = 0.25
  ) +
  geom_smooth(
    method = "glm",
    method.args = list(family = "binomial"),
    size = 1.2,
    se = TRUE,
    alpha = 0.35
  ) +
  scale_x_continuous(breaks = c(2, 6, 10, 14, 22, 30)) +
  scale_y_continuous(
    limits = c(-0.1, 1.1),
    breaks = c(0, 1),
    labels = c("Pup Initiation", "Mom Initiation")
  ) +
  scale_color_manual(values = c("#0033CC", "#606F19")) +
  scale_fill_manual(values  = c("#0033CC", "#606F19")) +
  labs(y = "Initiation<br><span style='font-size:11pt'>(Probability)</span>") +
  theme_classic() +
  theme(
    axis.title.x = element_text(size = 16),
    axis.title.y = ggtext::element_markdown(size = 16),
    axis.text = element_text(size = 13)
  )

```

```{r}
# General trend
ggplot(MomPupInitiation_vis,
       aes(PND, Choice)) +
  geom_jitter(
    position = position_jitterdodge(
      jitter.height = 0.05, jitter.width = 0.5, dodge.width = 0.5
    ),
    alpha = 0.25
  ) +
  geom_smooth(
    method = "glm",
    method.args = list(family = "binomial"),
    color = "darkgreen",
    fill = "darkgreen",
    size = 1.2,
    se = TRUE,
    alpha = 0.35   
  ) +
  scale_x_continuous(breaks = c(2, 6, 10, 14, 22, 30)) +
  scale_y_continuous(
  limits = c(-0.1, 1.1),
  breaks = c(0, 1),
  labels = c("Pup Initiation", "Mom Initiation")) +
  labs(y = "Initiation<br><span style='font-size:11pt'>(Probability)</span>") +
  theme_classic() +
theme(
  axis.title.x = element_text(size = 16),
  axis.title.y = ggtext::element_markdown(size = 16),
  axis.text = element_text(size = 13)
)
```


## Unsuccessful AND Successful Attachments

### Dataframe for Unsuccessful Attachments
```{r}

AttachmentFreq_behavs <- c("UNSUCCESSFUL ATTACHMENT", "SUCCESSFUL ATTACHMENT")

Success_Unsuccess <- MomPupBehav %>% 
  filter(Behaviour %in% AttachmentFreq_behavs) %>% 
  group_by(Behaviour, MomID, Rater, Condition, PND, ObservationID, PupID) %>%
  summarise(
    freq = sum(!is.na(Start_s)),
    .groups = "drop"
  )


Success_Unsuccess_Wide <- Success_Unsuccess %>%
  pivot_wider(
    names_from = Behaviour,
    values_from = freq,
    values_fill = NA) %>% 
  mutate(total = `SUCCESSFUL ATTACHMENT` + `UNSUCCESSFUL ATTACHMENT`,
         prop_success = `SUCCESSFUL ATTACHMENT`/total)


Success_Unsuccess_Wide2 <- Success_Unsuccess_Wide %>%
  mutate(
    `SUCCESSFUL ATTACHMENT`   = tidyr::replace_na(`SUCCESSFUL ATTACHMENT`, 0),
    `UNSUCCESSFUL ATTACHMENT` = tidyr::replace_na(`UNSUCCESSFUL ATTACHMENT`, 0),
    total = `SUCCESSFUL ATTACHMENT` + `UNSUCCESSFUL ATTACHMENT`
  ) %>%
  filter(total > 0)

```

```{r}

PropSuccessModel_00 <- glm(
  cbind(`SUCCESSFUL ATTACHMENT`,
        `UNSUCCESSFUL ATTACHMENT`) ~ Condition * PND,
    data = Success_Unsuccess_Wide2,
  family = binomial(link = "logit"))

PropSuccessModel_01 <- glmer(
  cbind(`SUCCESSFUL ATTACHMENT`,
        `UNSUCCESSFUL ATTACHMENT`) ~ Condition * PND +
    (1|PupID),
    data = Success_Unsuccess_Wide2,
  family = binomial(link = "logit"))

PropSuccessModel_02 <- glmmTMB(
  cbind(`SUCCESSFUL ATTACHMENT`,
        `UNSUCCESSFUL ATTACHMENT`) ~ Condition * PND +
    (1+Condition|PupID) +
    (1| MomID) +
    (1| ObservationID),
    data = Success_Unsuccess_Wide2,
  family = binomial(link = "logit")) # using this one rn 

PropSuccessModel_03 <- glmmTMB(
  prop_success ~ Condition * PND,
    data = Success_Unsuccess_Wide2,
  family = nbinom2) 


anova(PropSuccessModel_01, PropSuccessModel_02)

plot(simulateResiduals(PropSuccessModel_02)) 
performance::check_model(PropSuccessModel_02)

summary(PropSuccessModel_02)

```


### visualization
```{r}

ggplot(Success_Unsuccess_Wide2,
       aes(PND, prop_success, color = Condition, fill = Condition)) +
  geom_jitter(
    position = position_jitterdodge(
      jitter.height = 0.05, jitter.width = 0.5, dodge.width = 0.5
    ),
    alpha = 0.25
  ) +
  geom_smooth(
    method = "glm",
    method.args = list(family = "binomial"),
    size = 1.2,
    se = TRUE,
    alpha = 0.35
  ) +
  scale_x_continuous(breaks = c(2, 6, 10, 14, 22, 30)) +
  scale_color_manual(values = c("#0033CC", "#606F19")) +
  scale_fill_manual(values  = c("#0033CC", "#606F19")) +
  labs(y = "Attachment Success<br><span style='font-size:11pt'>(Proportion)</span>") +
  theme_classic() +
  theme(
    axis.title.x = element_text(size = 16),
    axis.title.y = ggtext::element_markdown(size = 16),
    axis.text = element_text(size = 13)
  )

```

## Mom Acceptance/Resistance 

### Dataframe
```{r}

Resist_Accept_behavs <- c("ACCEPTANCE", "RESISTANCE")

Accept_Resist <- MomPupBehav %>% 
  filter(Behaviour %in% Resist_Accept_behavs) %>% 
  dplyr::select(-Duration_s, -Stop_s, -Start_s, -BehaviourType, -Subject)

```

### Diagnostics
```{r warning = FALSE}

AcceptanceResistance_model_00 <- glm(
  Behaviour ~ Condition * PND,
  data = Accept_Resist, 
  family = binomial(link = "logit")) 

AcceptanceResistance_model_01 <- glmer( 
  Behaviour ~ Condition * PND +
    (1+PND|MomID) +
    (1 | PupID) +
    (1|Rater),  data = Accept_Resist, 
  family = binomial(link = "logit"))

AcceptanceResistance_model_02 <- glmer( 
  Behaviour ~ Condition * PND +
    (1+PND|MomID) +
    (1 + Condition | PupID) +
    (1|Rater),  data = Accept_Resist, 
  family = binomial(link = "logit"))

anova(AcceptanceResistance_model_02, AcceptanceResistance_model_01)

performance::check_model(AcceptanceResistance_model_02)
plot(simulateResiduals(AcceptanceResistance_model_00))
plot(simulateResiduals(AcceptanceResistance_model_01))
plot(simulateResiduals(AcceptanceResistance_model_02))

summary(AcceptanceResistance_model_02)

# 1+Pup:Condition? naur

```
### Visualization
```{r}

Accept_Resist_vis <- Accept_Resist %>% 
  filter(Behaviour %in% Resist_Accept_behavs) %>% 
  mutate(Choice = ifelse(Behaviour == "ACCEPTANCE", 1,0)) # 1 = mom, 0 = pup

ggplot(Accept_Resist_vis,
       aes(PND, Choice, color = Condition, fill = Condition)) +
  geom_jitter(
    position = position_jitterdodge(
      jitter.height = 0.05, jitter.width = 0.5, dodge.width = 0.5
    ),
    alpha = 0.25
  ) +
  geom_smooth(
    method = "glm",
    method.args = list(family = "binomial"),
    size = 1.2,
    se = TRUE,
    alpha = 0.35
  ) +
  scale_x_continuous(breaks = c(2, 6, 10, 14, 22, 30)) +
  scale_y_continuous(
    limits = c(-0.1, 1.1),
    breaks = c(0, 1),
    labels = c("Resistance", "Acceptance")
  ) +
  scale_color_manual(values = c("#0033CC", "#606F19")) +
  scale_fill_manual(values  = c("#0033CC", "#606F19")) +
  labs(y = "Acceptance/Resistance<br><span style='font-size:11pt'>(Probability)</span>") +
  theme_classic() +
  theme(
    axis.title.x = element_text(size = 16),
    axis.title.y = ggtext::element_markdown(size = 16),
    axis.text = element_text(size = 13)
  )
```


## Guidance 

### Dataframe
```{r}

Guidance <- MomPupBehav %>%
  filter(Behaviour == "GUIDANCE")

Guidance2 <- Guidance %>%
  group_by(MomID, Rater, Condition, PND, ObservationID, PupID) %>%
  summarise(
    freq = sum(!is.na(Start_s)),
    dur  = sum(Duration_s, na.rm = TRUE),
    .groups = "drop"
  )


```

```{r}

# frequency 

GuidanceModel_00 <- glm(
  freq ~ Condition * PND,
    data = Guidance2,
  family = nbinom2)

GuidanceModel_01 <- glmmTMB(
  freq ~ Condition * PND,
    data = Guidance2,
  family = nbinom2)

GuidanceModel_02 <- glmmTMB(
  freq ~ Condition * PND +
    (1+PND|MomID) + 
    (1+Condition|PupID),
    data = Guidance2,
  family = nbinom2) ## use this one? for now

summary(GuidanceModel_02)

GuidanceModel_03 <- glm.nb(
  freq ~ Condition * PND,
    data = Guidance2)

GuidanceModel_04 <- glmer.nb(
  freq ~ Condition * PND +
    (1+PND|MomID) +
    (1+Condition|PupID),
    data = Guidance2)


plot(GuidanceModel_00)
plot(simulateResiduals(GuidanceModel_00))
performance::check_model(GuidanceModel_00)

plot(simulateResiduals(GuidanceModel_01))
plot(simulateResiduals(GuidanceModel_02))
plot(simulateResiduals(GuidanceModel_03))


anova(GuidanceModel_01, GuidanceModel_02)


```

```{r}

GuidanceDurModel_00 <- glm(
  dur ~ Condition * PND,
    data = Guidance2,
  family = Gamma)

GuidanceDurModel_00 <- glmmTMB(
  dur ~ Condition * PND,
    data = Guidance2,
  family = gamma(link="log"))


GuidanceDur_binom_00 <- glm(
  dur > 0 ~ Condition * PND,
  family = binomial(link = "logit"),
  data = Guidance2)


GuidanceDur_binom_01 <- glmer(
  dur > 0 ~ Condition * PND +
    (1+PND | MomID) +
    (1+Condition | PupID),
  family = binomial(link = "logit"),
  data = Guidance2)

summary(GuidanceDur_binom_01)


plot(simulateResiduals(GuidanceDur_binom))

  
  GuidanceDuration_pos <- Guidance2 %>%
  filter(dur > 0)

GuidanceDur_gamma_00 <- glm(
  dur ~ Condition * PND,
  family = Gamma(link = "log"),
  data = GuidanceDuration_pos)  

GuidanceDur_gamma_01 <- glmmTMB(
  dur ~ Condition * PND +
    (1+PND | MomID) +
    (1+Condition | PupID) +
    (1|Rater),
  family = Gamma(link = "log"),
  data = GuidanceDuration_pos)

summary(GuidanceDur_gamma_01)


plot(simulateResiduals(GuidanceDur_gamma, group = GuidanceDuration_pos$PND))

plot(simulateResiduals(GuidanceDur_gamma, val = "zero"))

```

### Visualizations
```{r}

# frequency 

ggplot(Guidance2,
       aes(PND, freq, color = Condition, fill = Condition)) +
  geom_jitter(
    position = position_jitterdodge(
      jitter.height = 0.05, jitter.width = 0.5, dodge.width = 0.5
    ),
    alpha = 0.25
  ) +
  geom_smooth(
    method = "glm",
    method.args = list(family = "quasipoisson"),
    size = 1.2,
    se = TRUE,
    alpha = 0.35
  ) +
  scale_x_continuous(breaks = c(2, 6, 10, 14, 22, 30)) +
  scale_color_manual(values = c("#0033CC", "#606F19")) +
  scale_fill_manual(values  = c("#0033CC", "#606F19")) +
  labs(y = "Guidance Frequency") +
  theme_classic() +
  theme(
    axis.title.x = element_text(size = 16),
    axis.title.y = ggtext::element_markdown(size = 16),
    axis.text = element_text(size = 13)
  )

```
```{r}
# duration (binom)

ggplot(GuidanceDuration_pos,
       aes(PND, dur, color = Condition, fill = Condition)) +
  geom_jitter(
    position = position_jitterdodge(
      jitter.height = 0.05, jitter.width = 0.5, dodge.width = 0.5
    ),
    alpha = 0.25
  ) +
  geom_smooth(
    method = "glm",
    method.args = list(family = "Gamma"),
    size = 1.2,
    se = TRUE,
    alpha = 0.35
  ) +
  scale_x_continuous(breaks = c(2, 6, 10, 14, 22, 30)) +
  scale_color_manual(values = c("#0033CC", "#606F19")) +
  scale_fill_manual(values  = c("#0033CC", "#606F19")) +
  labs(y = "Guidance Duration") +
  theme_classic() +
  theme(
    axis.title.x = element_text(size = 16),
    axis.title.y = ggtext::element_markdown(size = 16),
    axis.text = element_text(size = 13)
  )
```

